### ISSUE TITLE
Image download returning error

### ISSUE THREAD

**Issue by gjedeer** [fsquillace/junest-site#1]
The link in docs is expired

https://dl.dropboxusercontent.com/u/42449030/junest/junest-x86_64.tar.gz 

< HTTP/1.1 404 Not Found
< Server: nginx
< Date: Thu, 12 Oct 2017 08:52:47 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Dropbox-Request-Id: 9433191ea6b23e61ccd3f1bb79b5b1a5
< X-Robots-Tag: noindex, nofollow, noimageindex
<

**Comment by fsquillace** [comment]
I have changed the website with the latest versions.

Everything should be fixed now.

Thanks!!
